### ISSUE TITLE
Use markers for data points

### ISSUE THREAD

**Issue by tanguilp** [elcritch/plotex#2]
Markers could be used for data points instead of https://github.com/elcritch/plotex/blob/master/lib/plotex/output/live_svg.ex#L214. The result would look "cleaner" and the file and websocket exchange would be lighter.

See also: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/marker

Just an idea :)

**Comment by elcritch** [comment]
That's a great idea! I looked into using pattern's but they didn't quite work. I think Markers would work perfectly. 

Another downside with the current method is to get the `rectangle`s and `circle`s centered require a bit of tweaking in the SVG. It also mean you can't really adjust the point size in CSS.

**Comment by elcritch** [comment]
Switched over to using SVG Markers in v0.3.0. It appears to be significantly faster. Thanks! 

Timing a test case on two of our IoT devices resulted in a time of ~14.28s for the old method and ~6.13s for the new. That's almost 2.32 times faster plotting about 80,000 data points. :-) Part of that will be DB access time too. 

Also added copied the "arrow" marker: 
https://github.com/elcritch/plotex/blob/63688377e365a1633db8317295c9d84058dcea4b/lib/plotex/output/svg.ex#L111

**Comment by tanguilp** [comment]
Cool! It'd be great to have the screenshots updated on the front page to see the result B)

Btw a long time ago, in this galaxy though, I made a website about SVG: http://svground.fr/. Even though it's written in French, I've been told that French has a certain degree of intelligibility for native English speakers, and there are a lot of examples. You might be interested browsing it.

I'll take a look and see if there are other possible optimizations.
