### ISSUE TITLE
Missing `Date` support

### ISSUE THREAD

**Issue by OvermindDL1** [elcritch/plotex#3]
For the X axis, it supports NaiveDateTime and DateTime, but not Date, instead it's crashing because it's trying to subtract two date structures due to the `def vals(a, _units), do: a` fallback online 51 in `view_range.ex`.  If it can't do a subtraction on the types then it should probably fail here instead of crashing when trying to subtract two maps.

**Comment by elcritch** [comment]
Great, thanks for the bug reports! I'll look into all the issues you filed next week.

**Comment by elcritch** [comment]
Apologies, I let this bitrot for so long. Not sure how to do this correctly, but I'll stick with the "unix" time hacks.
