### ISSUE TITLE
README.md is incorrect on `Plotex.Output.Svg.generate`

### ISSUE THREAD

**Issue by OvermindDL1** [elcritch/plotex#4]
In the README.md it has the line `Plotex.Output.Svg.generate(plt, xaxis: [rotate: 35, dy: '2.5em'], yaxis: [])`, however it fails because the second argument can't be a keyword list but rather must be an `Options` struct, which isn't mentioned of how to use in the readme at all.

**Comment by elcritch** [comment]
Unfortunately I never was able to document the API. The API was/is the hardest part. On the chance anyone else wants to use this, I've fixed the README and put a note to look in the plotex_test.ex where most of the options are used.
