### ISSUE TITLE
Calendar module is marked as optional, but appears to be required

### ISSUE THREAD

**Issue by OvermindDL1** [elcritch/plotex#5]
As per title, the calendar dependency is marked as `{:calendar, "~> 1.0.0", optional: true},`, however I can't seem to find a use that doesn't require it, always getting the exception of `function Calendar.Strftime.strftime/2 is undefined (module Calendar.Strftime is not available)`.  I think elixir has that functionality in it now as well (or at least has a PR for it), though not too hard to do it manually with Elixir's existing std functionality.

**Comment by elcritch** [comment]
It appears that `Calendar.Strftime.strftime` is now in the standard library. So I removed the Cldr versions and set calendar as required.
