### ISSUE TITLE
CSS Stroke is not set

### ISSUE THREAD

**Issue by OvermindDL1** [elcritch/plotex#6]
In the CSS the `stroke` is not set, so it uses what's on the page, which if is non-default then it makes the text unreadable.  The `stroke` value should be set on the entire svg back to an expected value (default is the value `none`, which is what I'm manually adding now).

**Comment by elcritch** [comment]
Thanks, that's an odd corner I'm not familiar with (or run into). I added it and it doesn't appear to break anything so I've added it.
